spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/users
    username: postgres
    password: test12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
