spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/products}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:test12345}
    driver-class-name: org.postgresql.Driver
