spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git: 
                    uri: https://github.com/halitkalayci/Microservices-Spring-GYGY5.git
                    default-label: master
                    search-paths: microservices/configs,microservices/configs/{application}
                    clone-on-start: true
                    force-pull: true
                native:
                    search-locations:
                        - file:../
                        - file:../{application}
                
server:
    port: 8888
