spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${BFF_CLIENT_ID:bff-client}
            client-secret: ${BFF_CLIENT_SECRET:spsyhj4VIM5bBBmdSyqjwVVmcF9CH3Lv}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8085/realms/microservices-gygy5}
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: gateway-server
              uri: lb://gateway-server
              predicates:
                - Path=/api/**
              filters:
                - TokenRelay

server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
