spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/v1/products/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
