spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:./configs
            - file:./configs/{application}
            - file:../configs
            - file:../configs/{application}
            - file:microservices/configs
            - file:microservices/configs/{application}

server:
  port: 8888
